### ISSUE TITLE
Abnormally high value of LAI and sPlantLeafArea

### ISSUE THREAD

**Issue by hdmarrou** [mariegosme/SSM.R#7]
1) order of magnitude (~~ 1000 times too big+ inconsistency between crops). Problem on LAI , DLAI, GLAI
2)no calculation after the first cycle

**Comment by achgls** [comment]
## Extremely high values of LAI observed (up to 15 000...)

When plotting variable "sLAI", we observe absurdly high values, rising up to 15 000...

Investigating sLAI computation, I noticed it's based upon "sPlantLeafArea", a.k.a "PLA", representing leaf area (in squared meters) for ONE individual plant. You'd get LAI by multiplying by plant density, 

Problem is, that variable rised up to 14 000 squared meters. I could easily figure that sLAI abnormal values resulted of a bug in PLA computation.

What does PLA itself depend on ? Its computation depends on "sMainstemNodeNumber",  a.k.a "MSNN", amongst other variables. Thing is, its value rose up to 1800... 1800 nodes on the main stem ? I am no botanist but it seems absurdly high.

After investigation, it seemed like the bug in MSNN computation - which resulted in absurd values of PLA, and thus LAI - depended on "daily_increase_node_number" being computed as so:

`daily_increase_node_number <- ALLDAYDATA$sThermalUnit / ALLDAYDATA$pPhyllochron`

sThermalUnit being the crop's CUMULATED thermal units since sowing...
A daily increase was being computed from a CUMULATED variable... It makes no sense and it should rather be computed from the DAILY increase in thermal units. Luckily, this variable already exists in ALLDAYDATA: "cDeltaThermalUnit".
I changed the code to:

`daily_increase_node_number <- ALLDAYDATA$cDeltaThermalUnit / ALLDAYDATA$pPhyllochron`

## LAI computation makes more sense now

![sLAI_fixed_maybe](https://user-images.githubusercontent.com/79403255/127169195-61d76479-560f-46dd-b3e6-23b13e5ccec1.JPG)

Considering order of magnitude, these values of LAI seem much more believable.
Values do seem a bit low, though ?  About up to 1 of LAI for wheat, 2-3 for chickpea.

For wheat, it might be due to the fact that growing basically stops for a long time shortly after sowing because of cCoefPhotoPeriod being = 0 (basically, growing for this wheat is completely stopped for day lengths of 11 hours and shorter.

![coefPhotoperiodforWheat](https://user-images.githubusercontent.com/79403255/127173283-422f7869-0ca9-4ee3-9a2c-3d006ebc13db.jpeg)

This also seems weird, but would be a different issue.

**Comment by achgls** [comment]
## ARE CURRENT VALUES OF LAI EFFECTIVELY A BIT LOW ? IF SO, WHAT WOULD BE THE CAUSE ? IF THEY ARE NOMINAL, HOWEVER, CONSIDER THIS ISSUE FIXED.

**Comment by achgls** [comment]
##  LAI WAS EFFECTIVELY A BIT LOW. FIXED. NOW: TOO HIGH
### CREATED ISSUE #19 
Low LAI was due to an error in crop managements having plant density = 30, when it should be ten times as much for wheat. Updated them to 280.
As a result, now LAI values are way too high for wheat, but quite nominal for chickpea:

![sLAI_still_too_high](https://user-images.githubusercontent.com/79403255/128035658-10ce39a5-1ac3-4973-ad75-2c4dbfd2dbe7.JPG)

Corresponding PLA (total leaf area by individual plant) and MSNN (main stem node number for one individual plant):

### PLA
![PLA](https://user-images.githubusercontent.com/79403255/128036180-36f29a3e-68c4-432e-b72e-4c320dc07a9c.png)

### MSNN
![MSNN](https://user-images.githubusercontent.com/79403255/128036214-3b3e2953-3001-4a17-86f4-c826098a6cba.png)
